model_provider = "openai_https"

model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"

[windows]
sandbox = "elevated"

[projects.'C:\Users\86191']
trust_level = "trusted"

[projects.'\\?\D:\work\ai lab\TrinityGuard']
trust_level = "trusted"

[projects.'D:\work\ai lab\skills_test\a']
trust_level = "trusted"

[projects.'D:\work\ai lab\skills_test\b']
trust_level = "trusted"

[projects.'D:\work\ai lab\skills_test']
trust_level = "trusted"

[projects.'D:\research\思路提出Agent']
trust_level = "trusted"

[projects.'D:\research\2026-EMNLP-纠错\impl']
trust_level = "trusted"

[projects.'\\?\D:\work\ai lab\TrinitySafeSkills']
trust_level = "trusted"

[projects.'D:\work\desktop-reminder']
trust_level = "trusted"

[projects.'\\?\D:\work\ai lab\TrinitySafeSkills\SentrySkills']
trust_level = "trusted"

[projects.'D:\work\腾讯智能体决策\code-gorge_chase-public-15.0.1-comp-normal-lite.26comp\code']
trust_level = "trusted"

[projects.'D:\work\ai lab\clawsentry_test']
trust_level = "trusted"

[projects.'D:\work\ai lab\skills-safety-bench-main\skills-safety-bench-main']
trust_level = "trusted"

[projects.'D:\work\ai lab\paper\sentryskill\benchmark\agentdojo']
trust_level = "trusted"

[projects.'D:\work\ai lab\paper\sentryskill']
trust_level = "trusted"

[projects.'D:\work\ai lab\paper\sentryskill\benchmark']
trust_level = "trusted"

[projects.'d:\research\goal-aware plan']
trust_level = "trusted"

[projects.'c:\users\86191\desktop\train_reward_model']
trust_level = "trusted"

[projects.'c:\users\86191\downloads\skill-safety-bench\skill-safety-bench']
trust_level = "trusted"

[projects.'c:\users\86191\appdata\roaming\edex-ui']
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
powershell_utf8 = false
collaboration_modes = true
steer = true
unified_exec = true
apps = false
multi_agent = true

[shell]
program = "cmd.exe"
args = ["/d", "/c"]

[tui.model_availability_nux]
"gpt-5.5" = 4



[model_providers.openai_https]
name = "OpenAI"
requires_openai_auth = true
supports_websockets = false
